# Generated by Django 3.1 on 2020-09-05 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopping_bag', '0003_auto_20200904_0641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32)),
                ('order_status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid')], default='created', max_length=50)),
                ('delivery_total', models.DecimalField(decimal_places=2, default=5.0, max_digits=100)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('bag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_bag.bag')),
            ],
        ),
    ]
