# Generated by Django 3.1 on 2020-09-07 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20200906_0808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing',
            old_name='is_active',
            new_name='active',
        ),
    ]
