# Generated by Django 3.1 on 2020-09-07 10:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_guestcheckout'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestcheckout',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='guestcheckout',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guestcheckout',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
