# Generated by Django 3.1 on 2020-09-08 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20200907_1014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuestCheckout',
        ),
    ]
