# Generated by Django 3.1 on 2020-09-15 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_orderlineitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderLineItem',
        ),
    ]
