# Generated by Django 3.1 on 2020-09-15 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_orderlineitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderLineItem',
        ),
    ]
