# Generated by Django 3.1 on 2020-09-03 12:45

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_bag', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bag',
            managers=[
                ('objcts', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='bag',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
