# Generated by Django 3.1 on 2020-09-04 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_bag', '0002_auto_20200903_1245'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bag',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='bag',
            old_name='sub_total',
            new_name='subtotal',
        ),
    ]
