# Generated by Django 3.1 on 2020-09-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_bag', '0005_auto_20200915_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
