# Generated by Django 3.1 on 2020-09-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_bag', '0006_bag_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='size',
            field=models.TextField(default=''),
        ),
    ]
