# Generated by Django 3.1 on 2020-09-19 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_bag', '0007_bag_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bag',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='bag',
            name='size',
        ),
    ]
