# Generated by Django 3.1 on 2020-09-19 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_bag', '0009_auto_20200919_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bag',
            old_name='order_line_item',
            new_name='order_line_items',
        ),
    ]
